---
resources:
- name: pcfapp
  type: git
  source:
    uri: https://github.com/shinyay/pcf-workshop-upgrade-code.git
    branch: master
  check_every: 10s
- name: deploy-to-cf
  type: cf
  source:
    api: api.run.pivotal.io
    username: <YOUR_USERID>
    password: <YOUR_PASSWD>
    organization: <YOUR_ORG>
    space: development
    skip_cert_check: true
jobs:
- name: unit-test
  plan:
  - get: pcfapp
    trigger: true
  - task: gradle-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          {repository: java, tag: openjdk-8}
      inputs:
      - name: pcfapp
      run:
        path: bash
        args:
        - -c
        - |
          cd pcfapp
          ./gradlew test
- name: build-and-deploy
  plan:
  - get: pcfapp
    passed: [ unit-test ]
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          {repository: java, tag: openjdk-8}
      inputs:
      - name: pcfapp
      outputs:
      - name: out
      run:
        path: bash
        args:
        - -c
        - |
          cd pcfapp
          ./gradlew clean build -x test
          mv build/libs/hello-pcf-upgrade-0.0.1-SNAPSHOT.jar ../out
  - put: deploy-to-cf
    params:
      manifest: pcfapp/manifest.yml
      current_app_name: hello-pcf-upgrade
      path: out/hello-pcf-upgrade-0.0.1-SNAPSHOT.jar